### ISSUE TITLE
LucidLin URL Changed

### ISSUE THREAD

**Issue by markkenny** [autopkg/moofit-recipes#150]
LucidLink/Lucid.pkg.recipe.yaml

It's now https://www.lucidlink.com/download and the packages are numbered. 

https://d3il9duqikhdqy.cloudfront.net/latest/osx/lucid-2.6.5463.pkg

I'm working on my version so offer a fix, but my autoPKG yaml skills are only marginally better than my regex ;-)

**Comment by markkenny** [comment]
[Got a working version as yaml.](https://github.com/markkenny/autopkg/blob/master/Lucid/Lucid.download.recipe.yaml)
```
Input:
  NAME: Lucid
  SEARCH_URL: https://www.lucidlink.com/download
  SEARCH_PATTERN: lucid-[0-9\.]*.pkg
  DOWNLOAD_URL: https://d3il9duqikhdqy.cloudfront.net/latest/osx

Process:
  - Processor: URLTextSearcher
    Arguments:
      re_pattern: "%SEARCH_PATTERN%"
      url: "%SEARCH_URL%"

  - Processor: URLDownloader
    Arguments:
      url: "%DOWNLOAD_URL%/%match%"
      filename: "%NAME%.pkg"
```
